server:
  port: 5000
spring:
  application:
    name: yjn-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    password: root
    port: 6379
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4GCNRahWnbBUbyTzDuma
    access-key-secret: GddN3bEygMU8zbp4vbCrybOPyQW7Zu
    bucket-domain: mytest977.oss-cn-beijing.aliyuncs.com
    bucket-name: mytest977
    end-point: oss-cn-beijing.aliyuncs.com
